Brook.groups
Endalebob/community-portal pull request #45
Opened 2023-06-28 20:25 UTC by BrookW-83

![Screenshot 2023-06-28 041036](https://github.com/Endalebob/community-portal/assets/109297876/dee3b8dc-d4be-4ca6-98b6-b629ab941464)
![Screenshot 2023-06-28 041113](https://github.com/Endalebob/community-portal/assets/109297876/ca3b22a3-bf70-4311-b1dd-78dbfe4548f5)
![Screenshot 2023-06-28 041137](https://github.com/Endalebob/community-portal/assets/109297876/ade25770-f990-43df-a5fe-5da71156d98e)
![Screenshot 2023-06-28 041209](https://github.com/Endalebob/community-portal/assets/109297876/19d2aa4d-2d43-453d-9edc-175cef126f0b)

2023-06-28 20:27 UTC, BrookW-83 commented
Try to add responsiveness to side bar

2023-06-29 07:24 UTC, jebessaD requested changes
Please ensure that any unused code is removed from the codebase.

2023-06-29 07:24 UTC, jebessaD commented on src/components/groups/CreateGroup.tsx
> +    try {
Use the default RTK query error to handle if there is a request error

2023-06-29 07:24 UTC, jebessaD commented on src/components/groups/CreateGroup.tsx
> +    } catch (errors) {}
If you find that a try-catch block is important and you need to do something after catching an error, perform the necessary actions in the catch block

2023-06-29 07:24 UTC, jebessaD commented on src/components/groups/CreateGroup.tsx
> +  const [onCreate, setCreat] = useState<boolean>(false);
Spelling error `setCreate` 
and make it  
const [showCreate, setShowCreate]

2023-06-29 07:24 UTC, jebessaD commented on src/components/groups/CreateGroup.tsx
> +  const handleCreat = () => {
Remove unused function

2023-06-29 07:24 UTC, jebessaD commented on src/components/groups/SideBar.tsx
> +  const handleAutofill = async (id: any) => {
If you don't need to perform any actions after autofill, you can remove the 'async/await' keywords.

2023-06-29 13:08 UTC, closed without merging